# Generated by Django 5.2.8 on 2025-11-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_name',
        ),
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(default='ул. Ленина, 1', max_length=200, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(default='Russian', max_length=100, verbose_name='Nationality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='passport_number',
            field=models.CharField(default='12345678', max_length=20, verbose_name='Passport Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
